name: Quick Tests (API Only)

# This workflow runs only fast API tests for quick feedback
# Use this for draft PRs or work-in-progress commits

on:
  push:
    branches: [ develop, feature/**, bugfix/** ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ develop ]

jobs:
  quick-api-tests:
    name: Quick API Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, sqlite, pdo_sqlite
          coverage: none
          
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        
      - name: Copy environment file
        run: cp .env.example .env.testing
        
      - name: Generate application key
        run: php artisan key:generate --env=testing
        
      - name: Create SQLite database
        run: touch database/database.sqlite
        
      - name: Run database migrations
        run: php artisan migrate --env=testing --force
        
      - name: Run API tests
        run: php artisan test --testsuite=Feature
        
      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}' === 'success' ? '✅ PASSED' : '❌ FAILED';
            const emoji = '${{ job.status }}' === 'success' ? '✅' : '❌';
            
            const comment = `## ${emoji} Quick API Tests
            
            **Status:** ${status}
            
            - ⚡ Fast API tests completed in ~2 minutes
            - 15 tests, 45+ assertions
            - Target: >98% success rate
            
            ${status.includes('FAILED') ? '⚠️ Full browser tests will run when merged to master/develop.' : '✅ Looking good! Full browser tests will run on merge.'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
